### ISSUE TITLE
odict_entry_add get wrong result in openwrt(ARM Architecture， 32bit)

### ISSUE THREAD

**Issue by lxlenovostar** [creytiv/re#112]
I use re in openwrt(ARM Architecture， 32bit). The test codes is:
![1](https://user-images.githubusercontent.com/444868/36673459-d5c3524a-1b3d-11e8-9c6a-c1a733f5e14f.jpg)

When I run in ubuntu (x86_64), It's Ok.
![2](https://user-images.githubusercontent.com/444868/36673500-ec05c3c6-1b3d-11e8-9395-ebf340ac6fbc.jpg)

But when I  cross-compiler and run it in openwrt(ARM 32bit), It's wrong.
![3](https://user-images.githubusercontent.com/444868/36673519-f827a5c0-1b3d-11e8-8344-94b8f80fe8c5.jpg)

How to solve it? 
Thank you.

**Comment by lgrahl** [comment]
`va_arg` doesn't cast on itself. I agree it's a nit people need to be aware of (and I need to fix it in RAWRTC) or we should consider changing it in re.

See: https://wiki.sei.cmu.edu/confluence/display/c/EXP47-C.+Do+not+call+va_arg+with+an+argument+of+the+incorrect+type

**Comment by alfredh** [comment]
the argument value to ODICT_INT must be of type `int64_t`

see the code in entry.c:

```
	case ODICT_INT:
		e->u.integer = va_arg(ap, int64_t);
		break;
```

I will update the documentation about this.

Alfred

**Comment by lxlenovostar** [comment]
Thank you.

**Comment by lxlenovostar** [comment]
Hi @alfredh @lgrahl
  
 Why this issue just happen on openwrt(arm 32bits), not ubuntu(x86_64 64bits)?

Thank you.

**Comment by lxlenovostar** [comment]
https://stackoverflow.com/questions/49041919/why-va-arg-produce-different-effects-on-x86-64-and-arm
