### ISSUE TITLE
Add link to Github from homepage

### ISSUE THREAD

**Issue by njh** [creytiv/re#115]
Hi,

I was initially put off by a broken link to Subversion on the libre homepage:
http://www.creytiv.com/re.html

Then I found the Github repo :)

Good to update the homepage to point to Github

nick.

**Comment by alfredh** [comment]
Thanks for reporting, I updated the homepage:

http://www.creytiv.com/re.html

please verify and close issue if ok.

Alfred

**Comment by njh** [comment]
Great! Thank you very much!
