### ISSUE TITLE
Broken example link on project

### ISSUE THREAD

**Issue by vit1251** [creytiv/re#120]
You have broken link in README docuemnt
Link http://creytiv.com/pub/redemo-0.4.1.tar.gz no more exists.

**Comment by alfredh** [comment]
Thanks for reporting! The server should be updated now.

https://github.com/creytiv/re/commit/bd037876112735fc1ca3e97a8391a084878153a2

**Comment by alfredh** [comment]
you can also use this Github project:

https://github.com/creytiv/redemo
