### ISSUE TITLE
OPTIONS request not implemented

### ISSUE THREAD

**Issue by bontric** [creytiv/re#126]
Hey there,
I'm currently working on a custom _re_-based UA implementation. I'm also trying to wrap my head around the SIP RFC and I noticed that the _re_ library does not seem to support the OPTIONS request, which [RFC 3261](https://tools.ietf.org/html/rfc3261#section-11) declares as a MUST for UAs:

> All UAs MUST support the OPTIONS method.

Now, I was wondering whether there is a specific reason for why it hasn't been implemented in _re_ ? (Note that, for my specific use case, I don't need to support the OPTIONS request but want to assure compatibility to the SIP RFC)

**Comment by alfredh** [comment]
Hi @bontric 

the SIP OPTIONS method is supported by libre.

for example it has been implemented in the Baresip SIP useragent:

https://github.com/alfredh/baresip/blob/master/src/ua.c#L551

and:

```c
int ua_options_send(struct ua *ua, const char *uri,
		    options_resp_h *resph, void *arg)
{
	struct mbuf *dialbuf;
	int err = 0;

	if (!ua || !str_isset(uri))
		return EINVAL;

	dialbuf = mbuf_alloc(64);
	if (!dialbuf)
		return ENOMEM;

	err = uri_complete(ua, dialbuf, uri);
	if (err)
		goto out;

	dialbuf->buf[dialbuf->end] = '\0';

	err = sip_req_send(ua, "OPTIONS", (char *)dialbuf->buf, resph, arg,
			   "Accept: application/sdp\r\n"
			   "Content-Length: 0\r\n"
			   "\r\n");
	if (err) {
		warning("ua: send options: (%m)\n", err);
	}

 out:
	mem_deref(dialbuf);

	return err;
}
```


most SIP methods are supported by libre. if your application wants to handle
and incoming OPTIONS for example, you must call the `sip_listen` function:

```c
	err = sip_listen(&uag.lsnr, uag.sip, true, request_handler, NULL);
	if (err)
		goto out;
```

and then check the method in request_handler.

hope this helps :)

Alfred

**Comment by bontric** [comment]
> most SIP methods are supported by libre. if your application wants to handle
and incoming OPTIONS for example, you must call the sip_listen function:

Ahh, I literally just checked the baresip code and found this solution! Thank you for the reply though, now I also know that this is the proper way to do it. Thanks a lot!
