### ISSUE TITLE
Build and install libre using MINGW

### ISSUE THREAD

**Issue by AlexanderplUs** [creytiv/re#128]
I build libre with MINGW using next command:
```
make -C $(libre_src_dir) \
		BUILD=$(libre_build_dir) \
		PREFIX= DESTDIR=$(install_dir) \
		CROSS_COMPILE= \
		all install
```
All works fine but there are some issues:
- Though all temporary files go to the `libre_build_dir`, resulted libre.a, libre.dll and libre.pc stay in original directory `libre_src_dir` which makes it dirty when checking with `git status`. Is there any way to put them in the `libre_build_dir `too?
- libre.dll is installed in the `$(DESTDIR)$(LIBDIR)` instead of `$(DESTDIR)/bin` which is correct place for it under MINGW. I think it is a bug because all other open source libraries put their dlls in `bin `directory.

**Comment by alfredh** [comment]
you can add this to your global `.gitignore` file:

```
libre.a
libre.dll
libre.pc
```

moving the location of libre.a I think will be difficult at this point in time.

for the second issue, the library is installed in LIBDIR for all platforms.
if you want to move it to `bin` perhaps you should consider adding some
post-build commands to your build scripts.

for windows I would recommend using the static .a library, I dont think
even that the .dll is working.

also see here:

https://github.com/alfredh/baresip-win32
