### ISSUE TITLE
No rules to build library with 64-bit Mingw

### ISSUE THREAD

**Issue by AlexanderplUs** [creytiv/re#129]
When I tried to build libre with 64-bit Mingw script `mk/re.mk` didn't detect that it is a WIN32 platform and build failed. As I checked mk/re.mk I found that it check output of `gcc -dumpmachine`. For 64-bit Mingw it gives `x86_64-w64-mingw32`

So, after I added this value to check in `mk/re.mk` libre compiles successfuly. Please consider to add support for 64-bit Mingw to the build scripts. Here is diff with my fix:
```
--- re.mk.orign 2018-04-15 15:56:52.531056000 +0400
+++ re.mk       2018-04-15 15:57:02.312273200 +0400
@@ -205,7 +205,7 @@


 ifneq ($(strip $(filter i386-mingw32 i486-mingw32 i586-mingw32msvc \
-       i686-w64-mingw32 mingw32, \
+       i686-w64-mingw32 x86_64-w64-mingw32 mingw32, \
        $(MACHINE))),)
        OS   := win32
 ifeq ($(MACHINE), mingw32)
```

**Comment by alfredh** [comment]
you can also have a look at this project for how to compile re/rem for mingw:

https://github.com/alfredh/baresip-win32

your change looks fine, would you like to create a PR for it ?

**Comment by richaas** [comment]
PR #131 merged to master
