### ISSUE TITLE
a signal handler with SIGSEGV

### ISSUE THREAD

**Issue by lxlenovostar** [creytiv/re#130]
I want to print call stack, when a SIGSEGV happen. 

```
void handle_signal_handler(int sig) {
 243     DEBUG_INFO("get signal: %d\n", sig);
 244     if (sig == SIGSEGV) {
 245         dump_trace();
 246     }                
 247      
 248     re_cancel();
 249 }   
```

In main function:
`2889     EOR(re_main(handle_signal_handler));`

I think handle_signal_handler will be call by signal 2(SIGINT), not signal 11(SIGSEGV). 

This  is why? Thank you.

**Comment by alfredh** [comment]
printing the call stack should be done with a debugger like gdb or lldb.

if you want to print the call stack in your program, you can try the `backtrace` function:

http://man7.org/linux/man-pages/man3/backtrace.3.html

Alfred
