### ISSUE TITLE
Android Oreo (8.0) support

### ISSUE THREAD

**Issue by Hmart** [creytiv/re#137]
Due to [changes](https://developer.android.com/about/versions/oreo/android-8.0-changes.html#o-pri) affecting privacy in android 8 trying to access the net.dns properties will result in the following:

```
E/libc: Access denied finding property "net.dns1"
E/libc: Access denied finding property "net.dns2"
E/libc: Access denied finding property "net.dns3"
E/libc: Access denied finding property "net.dns4"
```
Therefore for android versions >= 8 the following function will no longer work.
https://github.com/creytiv/re/blob/a3a44da128b0cd95c5edf7790bcf2e188b59d17d/src/dns/ns.c#L83

**Comment by sreimers** [comment]
not easy to fix, because there seems no native way to get the dns server without java JNI.
see: https://github.com/c-ares/c-ares/pull/148

**Comment by Hmart** [comment]
I did some research and found this thread on SO
https://stackoverflow.com/questions/3070144/how-do-you-get-the-current-dns-servers-for-android
I've managed to get a native implementation to work by implementing the method that executes the getprop command.

**Comment by alfredh** [comment]
hi @Hmart would you like to help to fix this issue? if you have some working code
perhaps you can submit a Pull Request ?

A workaround may be to statically configure a public DNS server (e.g. 8.8.8.8)
in the application.

Alfred

**Comment by juha-h** [comment]
@Hmart, did your getprop method call a java function via JNI?  Could you share your implementation?

**Comment by juha-h** [comment]
Alfred, are you suggesting that in case of libbaresip.a, src/net.c, dns_srv_get() calls would be modified to use 8.8.8.8?

**Comment by AlexanderplUs** [comment]
Is `get_android_dns ` function really needed in library? As I can see in the code it is used only in `dns_srv_get`  which is unused in library too. May be it is better to make external applications find this information themselves?

**Comment by alfredh** [comment]
hi @juha-h 

baresip can use the config option `dns_server` to add any custom nameservers.
I dont think we should hardcode any IP-address in the source code.

comment to @AlexanderplUs : 

the function `dns_srv_get` is unused in libre. The intention is that the application
can call it to get a list of nameservers from the OS. It is practical to have this function
available, but it is also limited to platforms that provide the needed APIs.

**Comment by alfredh** [comment]
I dont think we will find a good solution for this, so I suggest we close the ticket.

the recommendation will then be for the application to fetch the nameservers.
