### ISSUE TITLE
tls: no check of CA with openSSL 1.1.0

### ISSUE THREAD

**Issue by wnetbal** [creytiv/re#154]
I created a .pem file merging the 
-certificate
-key 
-ca

The TLS check is every time successful, also then when I use a wrong CA file.

It looks like the reason for this is that openSSL 1.1.0 does not set the verification methode by default.

**Comment by alfredh** [comment]
BTW, can you test if the same scenario works with OpenSSL 1.0.2 ?

**Comment by alfredh** [comment]
hi @wnetbal 

I added verification of certificates in the tls-test in retest:

https://github.com/creytiv/retest

could you please compile and run the tests on your machine?

```
cd retest
make
./retest -v -r
```


the test tests both positive and negative cases. In the negative case the
verification fails with 18  (X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT)
which is expected.
