### ISSUE TITLE
[CR]: Add support for mbedtls alongside openssl

### ISSUE THREAD

**Issue by rahmanih** [creytiv/re#157]
Hi,

For embedded systems, [mbedtls ](https://github.com/ARMmbed/mbedtls)is easier to integrate. is it possible to consider supporting it in future releases.

regards
Haithem.

**Comment by lgrahl** [comment]
I would support this intention (perhaps even write a PR later this year).

**Comment by alfredh** [comment]
have you tried to compile libre with mbedtls and see what happens ?

do they provide an openssl compatibility layer ?

**Comment by lgrahl** [comment]
Doesn't look like it.

> Mbed TLS does not yet offer an OpenSSL API. [...]

https://tls.mbed.org/openssl-alternative

**Comment by alfredh** [comment]
I added the item to the Roadmap here:

https://github.com/creytiv/re/wiki/Roadmap

This is a very large feature. Openssl alternatives is welcome,
and code contributions for this work is also welcome.


Alfred

**Comment by fire** [comment]
@alfredh Can you keep this issue open for tracking?

How does your workflow work for external proposals and work in progress?
