### ISSUE TITLE
How is SIP over DTLS transport supported?

### ISSUE THREAD

**Issue by avonjo** [creytiv/re#160]
How is SIP over DTLS transport supported?  Or did I misunderstood the feature set in the README.md

/** SIP Transport */
enum sip_transp {
        SIP_TRANSP_NONE = -1,
        SIP_TRANSP_UDP = 0,
        SIP_TRANSP_TCP,
        SIP_TRANSP_TLS,
        SIP_TRANSPC,
};

**Comment by alfredh** [comment]
DTLS protocol is supported.

SIP protocol is supported, with transports UDP, TCP or TLS.

SIP over DTLS is NOT supported. I have never seen any deployment of this.
Do you know any specific service or product that use SIP/DTLS ?


Alfred

**Comment by avonjo** [comment]
Hi,
Sorry, I misunderstood the "Features" in README.md

> UDP/TCP/TLS/DTLS transport

So it actually meant:

SIP supports UDP/TCP/TLS

The DTLS part is supported in STUN.
