### ISSUE TITLE
"struct ifreq" is undefined (compiling on musl)

### ISSUE THREAD

**Issue by josuah** [creytiv/re#171]
I am compiling on musl, and here is how /usr/share/include/net/if.h defines `struct ifreq`:

```

#if defined(_GNU_SOURCE) || defined(_BSD_SOURCE)

#include <sys/socket.h>

[...]

struct ifreq {
        [...]
};
```

It is not even an issue:

`CFLAGS=-D_BSD_SOURCE make` this works without a warning:

```
[...]
  CC      build-x86_64/rtmp/dechunk.o
  CC      build-x86_64/rtmp/hdr.o
  CC      build-x86_64/rtmp/stream.o
  LD      libre.so
  AR      libre.a
```

Maybe it's not worth adding `-D_BSD_SOURCE` for the sake of one header.  You are free to decide !

**Comment by alfredh** [comment]
hi @josuah 

musl is currently not a supported platform. For a list of supported platforms
see here:

https://github.com/creytiv/re#supported-versions-of-c-standard-library

you can also work around the issue by using `EXTRA_CFLAGS`

```
$ make EXTRA_CFLAGS=-D_BSD_SOURCE
```

**Comment by josuah** [comment]
Hi @alfredh

Thank you for your answer.
While musl is not a supported platform, it compiles without a warning on it. :)

With `make EXTRA_CFLAGS=-D_BSD_SOURCE` there is no modification to do for it to work.
