### ISSUE TITLE
bug, after add multithread synchronization for list

### ISSUE THREAD

**Issue by cloud-jxy** [creytiv/re#176]
I'm worried about list has multithreaded conflict. So, I code a patch. 

A open source program named baresip uses re. Baresip  url is https://github.com/alfredh/baresip.

I find baresip sip register fail after using my patch. The sip service don't recevie sip register request.

**Comment by cloud-jxy** [comment]
There is my patch.


[re_list.diff.zip](https://github.com/creytiv/re/files/2714231/re_list.diff.zip)

**Comment by alfredh** [comment]
`struct list` does not handle multi-threading on its own.

the code using the list must do its own mutex/locking if used with multiple threads.


Alfred

**Comment by kristate** [comment]
As @alfredh points-out, `struct list` does not handle multi-threading on its own, so you might want to look into [`mqueue`](https://github.com/creytiv/re/blob/e1125a53347bcb950a0a3cd59594f5a64e260f8a/include/re_mqueue.h).
