### ISSUE TITLE
Searching in generated docs.

### ISSUE THREAD

**Issue by alishir** [creytiv/re#179]
I found that `SEARCHENGINE` disabled in doxygen config file, is it possible to enable it?
According to doxygen documents, the default value is `YES`  and this feature disabled intentionally in `libre`.

**Comment by alfredh** [comment]
hi @alishir this option was disabled on purpose, because it made the doxygen pages
extremely slow.

you can enable it locally if you want:

1. set SEARCHENGINE YES
2. run `make dox`
3. open re-dox/html/index.html
