### ISSUE TITLE
Fail to link on OS/X Mojave - 14.2

### ISSUE THREAD

**Issue by oej** [creytiv/re#182]
I have checked that I have the latest Xcode and tools installed...

> LD      libre.dylib
> Undefined symbols for architecture x86_64:
>   "__mod_close", referenced from:
>       _mod_destructor in mod.o
>   "__mod_open", referenced from:
>       _mod_load in mod.o
>   "__mod_sym", referenced from:
>       _mod_load in mod.o
>   "_lock_alloc", referenced from:
>       _rtcp_sess_alloc in sess.o
>       _dynlock_create_handler in openssl.o
>   "_lock_read_get", referenced from:
>       _rtcp_stats in sess.o
>       _rtcp_debug in sess.o
>   "_lock_rel", referenced from:
>       _rtcp_sess_tx_rtp in sess.o
>       _rtcp_stats in sess.o
>       _rtcp_debug in sess.o
>       _mk_sr in sess.o
>       _dynlock_lock_handler in openssl.o
>   "_lock_write_get", referenced from:
>       _rtcp_sess_tx_rtp in sess.o
>       _mk_sr in sess.o
>       _dynlock_lock_handler in openssl.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
>

**Comment by alfredh** [comment]
libre compiles and links here on my OSX 14

you need to install system headers or specify `SYSROOT` as demonstrated here:

https://github.com/macports/macports-ports/blob/master/net/libre/Portfile
