### ISSUE TITLE
When SIP rcv buffer contains multiple messages, messages may be lost.

### ISSUE THREAD

**Issue by rmelch** [creytiv/re#193]
If the SIP receive buffer contains multiple messages, the second message may get lost.  

If there are remaining bytes in the buffer after a message has been parsed, these are saved for the next iteration of the parser.

```(void)mbuf_write_mem(mb, &conn->mb->buf[conn->mb->end],end - endOfSipMessage);```

I have noticed that `conn->mb->end` may be modified such that it no longer == `endOfSipMessage` causing the wrong number of bytes to be saved. This in turn caused the buffer to contain invalid SIP which the parser failed to decode eventually leading to  `sip_msg_decode()` returning `EBADMSG` due to overflow. 
My proposed fix is to use `endOfSipMessage` rather `conn->mb->end` than in the copy. 

```(void)mbuf_write_mem(mb, &conn->mb->buf[endOfSipMessage], end - endOfSipMessage);```

```
Subject: [PATCH] If there are unparsed bytes in the buffer, copy these
 starting from the end of the passed buffer.

---
 src/sip/transp.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/sip/transp.c b/src/sip/transp.c
index 2a74271..19bdf58 100644
--- a/src/sip/transp.c
+++ b/src/sip/transp.c
@@ -443,7 +443,7 @@ static void tcp_recv_handler(struct mbuf *mb, void *arg)
                        goto out;
                }
 
-               (void)mbuf_write_mem(mb, &conn->mb->buf[conn->mb->end],
+               (void)mbuf_write_mem(mb, &conn->mb->buf[endOfSipMessage],
                                     end - endOfSipMessage);
 
                mb->pos = 0;
-- 
2.17.1

```

**Comment by richaas** [comment]
Hi, this issue is likely caused by the fact that your application modifies msg->mb->end of the
received SIP messages. I would recommend that you treat the msg->mb buffer as read-only in your application to avoid issues like these. The msg->mb buffer points to the same memory buffer as subsequent messages. This design decision was done for performance reasons.

**Comment by rmelch** [comment]
OK I will check, Thanks.
