### ISSUE TITLE
sipreg/reg.c sent SIP headers problem

### ISSUE THREAD

**Issue by karanis** [creytiv/re#194]
Hi,
I'm having issues in sipreg/reg.c file line 266.
The client I`m using is baresip. I have a one-line _accounts_ file as instructed in the example :

`<sip:166@192.168.1.201;transport=udp>;auth_pass=xxxx`

When baresip tries to connect, the sent headers are (Contact part)

```
Contact: <sip:166-0x120fa20@192.168.1.88:58547>;expires=3778;+sip.instance="<urn:uuid:527e1172-083b-3eea-b54a-2976f6e3563a>"
    Contact URI: sip:166-0x120fa20@192.168.1.88:58547
        Contact URI User Part: 166-0x120fa20
        Contact URI Host Part: 192.168.1.88
        Contact URI Host Port: 58547
    Contact parameter: expires=3778
    Contact parameter: +sip.instance="<urn:uuid:527e1172-083b-3eea-b54a-2976f6e3563a>"\r\n
```

beware of **Contact URI User Part**, it has a trailing **-0x120fa20**

When I modify sipreg/reg.c file on line 266 

from
```
        err = mbuf_printf(mb, "Contact: <sip:%s@%J%s>;expires=%u%s%s",
                          reg->cuser, &reg->laddr, sip_transp_param(reg->tp),
```
to
```
        err = mbuf_printf(mb, "Contact: <sip:166@%J%s>;expires=%u%s%s",
                          &reg->laddr, sip_transp_param(reg->tp),

```
and force header manually, everything works fine and sent headers are turned to

```
Contact: <sip:166@192.168.1.88:32947>;expires=3795;+sip.instance="<urn:uuid:527e1172-083b-3eea-b54a-2976f6e3563a>"
    Contact URI: sip:166@192.168.1.88:32947
        Contact URI User Part: 166
        Contact URI Host Part: 192.168.1.88
        Contact URI Host Port: 32947
    Contact parameter: expires=3795
    Contact parameter: +sip.instance="<urn:uuid:527e1172-083b-3eea-b54a-2976f6e3563a>"\r\n
```

This is repeatable and same as of versions 0.5.9, 0.6.0 and git sources.
I don't think the code has errors but I`m stuck, any advice is highly appreciated. 

Thanks

Forgot to mention :
gcc (GCC) 7.2.0
GNU ld version 2.29.1

**Comment by GGGO** [comment]
Hi, what's your issue exactly ?

**Comment by karanis** [comment]
Hi, 
Problem is :

**Header function generates trailing characters for Contact URI User Part** 
in file src/sipreg/reg.c

(in my case, it adds -0x120fa20 to username).

**Error is repeatable.**

ldd libre.so output is :
```
        linux-vdso.so.1 (0x00007ffcf05e5000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fb096dc2000)
        libssl.so.1 => /lib64/libssl.so.1 (0x00007fb096b50000)
        libcrypto.so.1 => /lib64/libcrypto.so.1 (0x00007fb0966fd000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fb0964e6000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb0962c7000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb095ee8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb09724e000)
```



Thank you.

**Comment by alfredh** [comment]
it is not an error, it is how it is designed.

please take a look at baresip source code in ua.c:

https://github.com/alfredh/baresip/blob/master/src/ua.c#L684

**Comment by karanis** [comment]
Wow, I am so confused. I`ll examine it more upon your advice but it prevents user login / subscription on my test platform for Karel PBX system. Very funny. Looks like server side implementation lacks conforming standards after your reply as far as I can understand. I will investigate more and post solution asap for the (so called target) platform. Thank you again.

**Comment by karanis** [comment]
Thank you very very much. The code you`ve led me thru is the answer. 
(modifying the codeline you`ve mentioned solved it.)

**Comment by karanis** [comment]
The problem I`ve faced was about registering to a Karel branded PBX.
This is most probably a manufacturer issue.
