### ISSUE TITLE
do you and your team have the plane to support rtcp-fb NACK/RTX/TMMBR and etc ?

### ISSUE THREAD

**Issue by ZhuChasel** [creytiv/re#202]
Dear Team,
         It's a pitty the rtcp feedback part is not full support, thus like NACK/RTX/TMMBR, etc. So,  do you and your team have the plane to support these items? For Embedded program, libre is tiny and in good work. More rtcp-fb support and jitterbuffer achieve perfection  will have an effort to  complex and bad netwok env.
Thanks.

**Comment by alfredh** [comment]
thanks for your input.

RTCP NACK is already supported.
https://github.com/creytiv/re/blob/master/include/re_rtp.h#L34


I have added the other items to the roadmap:

https://github.com/creytiv/re/wiki/Roadmap

**Comment by ZhuChasel** [comment]
Dear alfredh. Thanks for your remind that RTCP NACK is already supported. But it seems that the rtcp-feedback working on jitterbuffer do not support, for example , receiving NACK and cooperating jitterbuffer to sending out corresponding rtp packet, like getNackList in webrtc.  Or, you think my understanding is wrong.
