### ISSUE TITLE
Memory leak when terminating redemo with Ctrl-C

### ISSUE THREAD

**Issue by alishir** [creytiv/re#204]
`sip_ua` compiled successfully, but the program still running when I tried to close it with `Ctrl-C`. I modified the `terminate` function and added more `mem_deref` lines, but now I get memory leaks. The following are the terminate function and the memory leaks error.

```c
  static void terminate(void) {
    /* terminate session */
    re_printf("in terminate function\n");
    sipsess_close_all(sess_sock);
    sip_close(sip, true);

    sdp = mem_deref(sdp); /* will also free sdp_media */
    rtp = mem_deref(rtp);
    sess = mem_deref(sess);
    sess_sock = mem_deref(sess_sock);
    sip = mem_deref(sip);
    re_printf("num of ref to sdp: %d\n", mem_nrefs(sdp));
    re_printf("num of ref to rtp: %d\n", mem_nrefs(rtp));
    re_printf("num of ref to sess: %d\n", mem_nrefs(sess));
    re_printf("num of ref to sess_sock: %d\n", mem_nrefs(sess_sock));
    re_printf("num of ref to sip: %d\n", mem_nrefs(sip));

   tmr_debug();
   mem_debug();
   fd_debug();
}

```

The program output:
```
num of ref to sdp: 0
num of ref to rtp: 0
num of ref to sess: 0
num of ref to sess_sock: 0
num of ref to sip: 0
mem: Memory leaks (3):
  0xcf9050: nrefs=1  size=1640    [00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ] [................]
  0xd16b40: nrefs=1  size=24576   [00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ] [................]
  0xd1cb90: nrefs=1  size=12288   [00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ] [................]

```

Would you please help to resolve this memory leak issue? I also tried `re_cancel` in the `terminate` function but it cause SIGSEGV error.

**Comment by richaas** [comment]
Hi @alishir, the program will not exit immediately when you hit ctrl-c by intention. This is because it needs to make sure that all registrations and sessions are terminated properly before shutting down.
So the shutdown process is asynchronous; first terminate() is called upon ctrl-c, then exit_handler() is called when the SIP stack is done with terminating all sessions/registrations.

The sip_close() function has a `force` argument that can be used to avoid the above behaviour, but this is not recommended.

**Comment by alishir** [comment]
Hi @richaas, thanks for your guidance. I changed the code according to your comment, but I got memory leak again. Can I detect leaked objects based on their size?

```c
  /* terminate */
  static void terminate(void) {
    /* terminate session */
    re_printf("in terminate function\n");
    re_printf("number of clients: %d\n", list_count(&clients));
    sdp = mem_deref(sdp); /* will also free sdp_media */
    rtp = mem_deref(rtp);
    sess = mem_deref(sess);
    list_flush(&clients);

    sip_close(sip, false);
  }

  /* called when all sip transactions are completed */
  static void exit_handler(void *arg) {
    (void)arg;
    re_printf("exit_handler\n");

    sess_sock = mem_deref(sess_sock);
    sip = mem_deref(sip);
    re_printf("num of ref to sdp: %d\n", mem_nrefs(sdp));
    re_printf("num of ref to rtp: %d\n", mem_nrefs(rtp));
    re_printf("num of ref to sess: %d\n", mem_nrefs(sess));
    re_printf("num of ref to sess_sock: %d\n", mem_nrefs(sess_sock));
    re_printf("num of ref to sip: %d\n", mem_nrefs(sip));

    /* stop libre main loop */
    re_cancel();

    tmr_debug();
    mem_debug();
    fd_debug();
  }

```

I also should not that I have some modification in `sip_ca.c`, I removed registration block and added simple listener to store other clients info. Here is the complete source file: https://gist.github.com/alishir/2ca90e5049f33b367778f8b94c2babcc

**Comment by richaas** [comment]
You can't check for memory leaks in the exit_handler. All memory is not freed yet here. Use the original check at the end of the main() function.

**Comment by alishir** [comment]
Thanks a lot, the issue resolved.
