### ISSUE TITLE
Does libre supports multipart/mixed content-type?

### ISSUE THREAD

**Issue by alishir** [creytiv/re#211]
Hi all,

Does libre supports this type of content-type: `Content-Type: multipart/mixed; boundary=[mytag]`?

**Comment by alfredh** [comment]
The issue tracker is for reporting defects and bugs.

For questions please use the mailing-list:

http://lists.creytiv.com/mailman/listinfo/re-devel

libre does not support multipart/mixed, however it is supported
by baresip:

https://github.com/alfredh/baresip/blob/master/src/sdp.c#L114

you can reuse the code if you wish.
