### ISSUE TITLE
compile on mac

### ISSUE THREAD

**Issue by Ola-Palm** [creytiv/re#214]
Hello. I get this error when compiling on 
Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
make CC=clang
`
..... CC      build-x86_64/rtmp/ctrans.o
  CC      build-x86_64/rtmp/dechunk.o
  CC      build-x86_64/rtmp/hdr.o
  CC      build-x86_64/rtmp/stream.o
  LD      libre.dylib
Undefined symbols for architecture x86_64:
  "__mod_close", referenced from:
      _mod_destructor in mod.o
  "__mod_open", referenced from:
      _mod_load in mod.o
  "__mod_sym", referenced from:
      _mod_load in mod.o
  "_lock_alloc", referenced from:
      _rtcp_sess_alloc in sess.o
      _dynlock_create_handler in openssl.o
  "_lock_read_get", referenced from:
      _rtcp_stats in sess.o
      _rtcp_debug in sess.o
  "_lock_rel", referenced from:
      _rtcp_sess_tx_rtp in sess.o
      _rtcp_stats in sess.o
      _rtcp_debug in sess.o
      _mk_sr in sess.o
      _dynlock_lock_handler in openssl.o
  "_lock_write_get", referenced from:
      _rtcp_sess_tx_rtp in sess.o
      _mk_sr in sess.o
      _dynlock_lock_handler in openssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libre.dylib] Error 1
`
Any suggestions ?

**Comment by alfredh** [comment]
please see this one:

https://github.com/creytiv/re/issues/191
