### ISSUE TITLE
DNS client only queries first server (in most cases)

### ISSUE THREAD

**Issue by fwjavox** [creytiv/re#216]
When there is more than one DNS server and the first one has no entry that matches the request, the DNS client will not query the next servers.
This patch fixes the problem, but since the structure is pretty complex I'm not sure about possible side-effects.
```
diff --git a/src/dns/client.c b/src/dns/client.c
index 9535e07..76bcea5 100644
--- a/src/dns/client.c
+++ b/src/dns/client.c
@@ -229,7 +229,7 @@ static int reply_recv(struct dnsc *dnsc, struct mbuf *mb)
        }
 
        /* try next server */
-       if (dq.hdr.rcode == DNS_RCODE_SRV_FAIL && q->ntx < *q->srvc) {
+       if (dq.hdr.rcode != DNS_RCODE_OK && q->ntx < *q->srvc) {
 
                if (!q->tc) /* try next UDP server immediately */
                        tmr_start(&q->tmr, 0, udp_timeout_handler, q);
```

**Comment by alfredh** [comment]
if you have 2 DNS servers, I think both of them should reply with exactly
the same answer for a given query.

adding @partim who is a DNS expert.

**Comment by partim** [comment]
Correct. An answer with an RCODE of NoError and no records in the answer section indicates that there are no records for the requested name and record type.

**Comment by alfredh** [comment]
Thanks for your valuable answer Dr. Hoffmann :)

The ticket can be closed now.

**Comment by fwjavox** [comment]
I didn't know that. Thanks for your answer! So the problem is our testing setup where we have local DNS entries in a local server that are not resolved by external DNS servers.

**Comment by partim** [comment]
Ah, yes. In this case you probably should only use internal servers that also resolve external names. Unbound happily does this for you – use a stub zone if you want to keep your authoritative for these zones separately or auth zones if you want Unbound to load those zones directly from a file.
