### ISSUE TITLE
Can I use libre and librem in windows applications? How to compile as dll?

### ISSUE THREAD

**Issue by Varooneh** [creytiv/re#237]
Hi,
I need libre and librem for windows, I want use in Delphi or C#. First, Can I use libre and librem in Delphi or C#? and how to create dll?

Please help me.

Thank you.

**Comment by Encamy** [comment]
Hello,
Yes you can
You can use visual studio project [re/mk/win32](https://github.com/creytiv/re/tree/master/mk/win32) with combination of rem project [rem/mk/win32](https://github.com/creytiv/rem/tree/master/mk/win32)  
Look at example of compiling stack of re/rem/baresip at [baresip/mk/win32](https://github.com/alfredh/baresip/tree/master/mk/win32)

Modify this project files for your need or create your own from scratch. Then compile it as dynamic library (dll) and use in your Delphi or C# projects

**Comment by Varooneh** [comment]
Hi @Encamy 
Thank you for help me, I used visual studio 2015 and visual studio 2019. When I open libre in vs 2015 or 2019 I can only build .lib, when I changed to dll I got multiple errors and can not create dll, but .lib have not any problem. I can not use .lib id delphi or c#.

Can you help me how to combine libre and librem and build as dll?

I checked baresip repo but I can not find any solution or reference for libre and librem.

Please help me.

(sorry for bad english)

**Comment by Varooneh** [comment]
@Encamy 
Also I read this [link ](https://github.com/creytiv/re/issues/150#issuecomment-413457602) and i get many errors

**Comment by Encamy** [comment]
I've tried to compile re dll, seem like you need to add `Ws2_32.lib` and `Iphlpapi.lib` to additional dependencies for linker. Also you need to include file http/chunk.c to compilation, I don't understand why project complies without it btw:)

I think you need do the same thing for rem.

>I checked baresip repo but I can not find any solution or reference for libre and librem.

Probably, it's much easier to use baresip solution project [alfredh/baresip/win32/baresip.sln](https://github.com/alfredh/baresip/tree/master/mk/win32/baresip.sln) and compile only re/rem.

About `Gm` option: sometime it will be deprecated in future realease of VS, but now it is OK. Maybe project need to be upgraded, but then users with VS15 or VS17 won't be able to compile project.

**Comment by Varooneh** [comment]
@Encamy 
After several attempts, with your help, I could create dll for libre and very very thank you for help me.
For librem, I used libre solution but I received several error. Librem isn't important for my usage.
Again, thank you for help.
Good luck :-)

**Comment by Encamy** [comment]
@Varooneh sorry, I didn't see your message
The best way is to create a wrapper with functional that you need and declare functions with `_cdecl` and `__declspec(dllexport)`

**Comment by Varooneh** [comment]
@Encamy Thank you for help.
