### ISSUE TITLE
Release libre version 0.5.0

### ISSUE THREAD

**Issue by alfredh** [creytiv/re#30]
Release libre v0.5.0

* test on supported platforms
* update documentation

Testing:

* Android NDK r13 (arm)
* CentOS 7.2 (x86_64) retest@1ae43f24fd602e3a529acae73d85800ba62c9a2f
* Debian 8.6 (i386)
* Fedora 24
* Mingw32 gcc 3.4.5 with OpenSSL 1.1.0c and WINE
* OpenWRT 15.05 Chaos Calmer (mips) with baresip
* OSX 10.12 (x86_64)
* Ubuntu 14.04 (x86_64)

**Comment by oej** [comment]
Just cloned and run "make"...
OS/X 10.11.6 El Capitain
```
  CC      build-x86_64/json/encode.o
  LD      libre.dylib
Undefined symbols for architecture x86_64:
  "__mod_close", referenced from:
      _mod_destructor in mod.o
  "__mod_open", referenced from:
      _mod_load in mod.o
  "__mod_sym", referenced from:
      _mod_load in mod.o
  "_lock_alloc", referenced from:
      _rtcp_sess_alloc in sess.o
      _dynlock_create_handler in openssl.o
  "_lock_read_get", referenced from:
      _rtcp_stats in sess.o
      _rtcp_debug in sess.o
  "_lock_rel", referenced from:
      _rtcp_sess_tx_rtp in sess.o
      _rtcp_stats in sess.o
      _rtcp_debug in sess.o
      _mk_sr in sess.o
      _dynlock_lock_handler in openssl.o
  "_lock_write_get", referenced from:
      _rtcp_sess_tx_rtp in sess.o
      _mk_sr in sess.o
      _dynlock_lock_handler in openssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libre.dylib] Error 1

```

**Comment by alfredh** [comment]
thanks Olle. is Xcode Command-line tools installed on your machine ?

I added some extra info in the Wiki:

https://github.com/creytiv/re/wiki/Installation

**Comment by oej** [comment]
Yes, they are.

**Comment by alfredh** [comment]
can you please paste the output of `make info` here ?

is this header file present in your system:

```
/usr/include/dlfcn.h 
```

**Comment by oej** [comment]
´´´
info - re version 0.5.0
  MODULES:       sip sipevent sipreg sipsess uri http httpauth msg websock stun turn ice natbd rtp sdp jbuf telev dns md5 crc32 sha hmac base64 udp sa net tcp tls list mbuf hash fmt tmr main mem dbg sys lock mqueue mod conf bfcp aes srtp odict json
  MACHINE:       x86_64-apple-darwin15.6.0
  ARCH:          x86_64
  OS:            darwin
  BUILD:         build-x86_64
  CCACHE:        
  CC:            clang 8.0
  CFLAGS:        -I/opt/local/include -Wall -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wbad-function-cast -Wsign-compare -Wnested-externs -Wshadow -Waggregate-return -Wcast-align -g -fPIC -dynamic -DDARWIN -Wshorten-64-to-32 -DOS="darwin" -std=c99 -pedantic -DARCH="x86_64" -DUSE_OPENSSL -DUSE_TLS -DUSE_OPENSSL_DTLS -DUSE_DTLS -DUSE_OPENSSL_SRTP -DUSE_DTLS_SRTP -DUSE_ZLIB -DHAVE_STRERROR_R -DHAVE_STDBOOL_H -DHAVE_INET6 -DHAVE_FORK -DHAVE_INET_NTOP -DHAVE_PWD_H -DHAVE_SELECT -DHAVE_SELECT_H -DHAVE_SETRLIMIT -DHAVE_SIGNAL -DHAVE_SYS_TIME_H -DHAVE_KQUEUE -DHAVE_UNAME -DHAVE_UNISTD_H -DHAVE_STRINGS_H -DHAVE_GAI_STRERROR -DVERSION="0.5.0"  -Iinclude
  DFLAGS:        -MD
  LFLAGS:        -L/opt/local/lib -fPIC  -framework SystemConfiguration -framework CoreFoundation
  SH_LFLAGS:     -dynamiclib -current_version 0.5.0 -compatibility_version 0.5.0
  MOD_LFLAGS:    -undefined dynamic_lookup
  APP_LFLAGS:    
  LIBS:          -lresolv -lssl -lcrypto -lz
  LIBRE_MK:      
  LIBRE_INC:     ../re/include
  LIBRE_SO:      /usr/local/lib
  USE_OPENSSL:   yes
  USE_OPENSSL_AES:   yes
  USE_OPENSSL_HMAC:  yes
  USE_TLS:       yes
  USE_DTLS:      yes
  USE_DTLS_SRTP: yes
  USE_ZLIB:      yes
  GCOV:          
  GPROF:         
  CROSS_COMPILE: 
  SYSROOT:       /usr
  SYSROOT_ALT:   /opt/local
  LIB_SUFFIX:    .dylib
  MOD_SUFFIX:    .so
  BIN_SUFFIX:    
´´´

**Comment by oej** [comment]
/usr/include/dlfcn.h  does not exist

**Comment by alfredh** [comment]
is anyone else having problems with this ?

I have Xcode and Command-line tools installed (Sierra) and dlfcn.h is present.

**Comment by alfredh** [comment]
Released!

http://lists.creytiv.com/pipermail/re-devel/2016-November/001143.html

**Comment by markandrus** [comment]
I had the same issue as @oej. I resolved it by setting `SYSROOT`:

```
make clean
SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr make
```
