### ISSUE TITLE
Issue when a route contains a sips scheme

### ISSUE THREAD

**Issue by tgueslin** [creytiv/re#39]
Configuring baresip in tls.
The SIP infrastructure adds some route headers.
If one of this route has a "sips" scheme, the call can't be established (error in sending the ack).
"function not implemented"

Here is a proposed patch:

------------------------------ src/sip/request.c ------------------------------
index aca2935..9e4dd6c 100644
@@ -606,7 +606,7 @@ int sip_request(struct sip_request **reqp, struct sip *sip, bool stateful,
	if (!sip || !met || !uri || !route || !mb)
		return EINVAL;

-	if (pl_strcasecmp(&route->scheme, "sip"))
+	if (pl_strcasecmp(&route->scheme, "sip") && pl_strcasecmp(&route->scheme, "sips"))
		return ENOSYS;

**Comment by richaas** [comment]
The SIPS URI scheme is not supported by libre. Adding support for SIPS would take a lot more than the suggested modification above. See RFC3261 for details.

**Comment by alfredh** [comment]
the SIPS uri guarantees that each hop between user A and user B is using
a secure transport (TLS).

see this RFC for details: https://tools.ietf.org/html/rfc5630
