### ISSUE TITLE
Add support for openssl 1.1.0

### ISSUE THREAD

**Issue by ggarber** [creytiv/re#4]
There are 2 main issues:
- Many structures are forward declared now in openssl (hmac_ctx_st, bio_st...) and libre is trying to create them in the stack and/or access their fields.
- All the threading APIs (CRYPTO_num_locks, CRYPTO_LOCK ....) have been removed because now threading support is implemented internally in openssl.

**Comment by alfredh** [comment]
Hey Gustavo,

I have been working on adding support for OpenSSL 1.1.0

could you please try out this branch:

https://github.com/creytiv/re/tree/openssl-1.1.0


we aim to support all versions of openssl from 0.9.8 to 1.1.x

**Comment by ggarber** [comment]
That's great, thank you for this.  

It is working perfectly in all the tests I did so far.

**Comment by alfredh** [comment]
still a couple a warnings to fix:

```
src/tls/openssl/tls.c: In function `tls_alloc':
src/tls/openssl/tls.c:100: warning: `DTLSv1_method' is deprecated (declared at /Users/alfredh/git/baresip-win32/openssl/include/openssl/ssl.h:1614)
src/tls/openssl/tls.c:111: warning: `DTLSv1_2_method' is deprecated (declared at /Users/alfredh/git/baresip-win32/openssl/include/openssl/ssl.h:1620)
```

what kind of platforms have you tested on?

**Comment by ggarber** [comment]
I tested it in MacOS, I will try to test it in Linux next.  Maybe I was compiling with doesn't treat warnings and errors, not sure.

Regarding those methods (DTLSvX_method) I use them directly in other parts of my project and I replaced them with DTLS_method without having any further problem so far.

**Comment by alfredh** [comment]
I would like to ask for help regarding code review and testing of this branch.

one thing which I want to improve is the creation of BIO_METHOD object for sending
and receiving TCP/UDP packets:

```
+#if OPENSSL_VERSION_NUMBER >= 0x10100000L
+       BIO_METHOD *method;  /* XXX: can move to a shared state? */
+#endif
```

**Comment by alfredh** [comment]
fixed in https://github.com/creytiv/re/commit/afa2f1e21ecf2ef607949f68894dfab3bbf11d33
