### ISSUE TITLE
Implicit declaration warning on FreeBSD 11

### ISSUE THREAD

**Issue by lgrahl** [creytiv/re#48]
Hey, I noticed that FreeBSD 11 spits out a warning when compiling re:

```
  CC      build-x86_64/tls/openssl/tls.o
src/tls/openssl/tls.c: In function 'tls_srtp_keyinfo':
src/tls/openssl/tls.c:736:2: warning: implicit declaration of function 'SSL_get_selected_srtp_profile' [-Wimplicit-function-declaration]
  sel = SSL_get_selected_srtp_profile(tc->ssl);
  ^
src/tls/openssl/tls.c:736:2: warning: nested extern declaration of 'SSL_get_selected_srtp_profile' [-Wnested-externs]
src/tls/openssl/tls.c:736:6: warning: assignment makes pointer from integer without a cast
  sel = SSL_get_selected_srtp_profile(tc->ssl);
      ^
```

OpenSSL version: `OpenSSL 1.0.2j-freebsd  26 Sep 2016`

**Comment by alfredh** [comment]
this must be a bug in FreeBSD packaging of OpenSSL.

https://github.com/freebsd/freebsd-ports/blob/master/security/openssl/files/patch-srtp.h

**Comment by alfredh** [comment]
we should report this issue to the FreeBSD maintainers.

Hi @mat813, we are having a problem building libre for FreeBSD 11.
it looks like this function has been removed from OpenSSL:

`SSL_get_selected_srtp_profile()`

is there a reason for this ?

**Comment by mat813** [comment]
I have absolutely no clue.

**Comment by lgrahl** [comment]
Do you know anyone we can ping about this? :)

**Comment by mat813** [comment]
Mmm, @Sp1l is our ssl guy.

**Comment by alfredh** [comment]
the srtp patch was added in this commit:

commit 4eeb11d1f22bda2546267cc93a229730891d1310
Author: dinoex <dinoex@FreeBSD.org>
Date:   Sat Mar 21 10:53:13 2015 +0000

**Comment by Sp1l** [comment]
This patch was already present in the 1.0.1 branch, see commit freebsd/freebsd-ports@73d8b56ed66b231df4111e0a00db4b14a990bc04 
Commit log-entry indicates it was added to fix a build-error when compiling with `-Werror`

I think we can safely assume that this patch is no longer required. Testing in progress...

**Comment by Sp1l** [comment]
Fixes are in review.
FreeBSD base: https://reviews.freebsd.org/D10525
FreeBSD ports: https://reviews.freebsd.org/D10523

Please test and let me know if this resolves the issue.

**Comment by lgrahl** [comment]
@Sp1l Seems to work. Applied the patch locally and the warning is gone. :)

**Comment by alfredh** [comment]
@Sp1l many thanks for your fixes. Do you know when they will be available in FreeBSD 11 ?

**Comment by alfredh** [comment]
since the bug is in FreeBSD and not libre, closing issue.
