### ISSUE TITLE
Add release tags

### ISSUE THREAD

**Issue by fancycode** [creytiv/re#5]
First of all, thanks for finally migrating to Git :+1:

It would be awesome if you could also push the release tags as Git tags so people can get these releases from a Git clone.

**Comment by alfredh** [comment]
the latest release was 0.4.17

how many releases do you need git tags for ?

**Comment by alfredh** [comment]
I added 3 releases for 0.4.15 to 0.4.17

https://github.com/creytiv/re/releases

any future release will of course be tagged.

**Comment by fancycode** [comment]
perfect, thanks!
