### ISSUE TITLE
Unknown format specifier handling

### ISSUE THREAD

**Issue by lgrahl** [creytiv/re#51]
In case a format specifier is not known, re's `re_vhprintf` function simply ignores it. This can lead to segfaults because the argument provided for that format specifier will then be applied on the following format specifier. That doesn't seem ideal to me. The function already returns an error but maybe it's better to fail the function once it finds an unknown format specifier? What do you think?

**Comment by alfredh** [comment]
a simple test program:

```
	printf("%y\n", 123);
	re_printf("%y\n", 123);
```

will give this output:

```
%y
?
```

i.e. GNU libc printf prints the formatter, while libre prints a question mark.

an example with two arguments:

```
	printf("%y %s\n", 123, "abc");
	re_printf("%y %s\n", 123, "abc");
```

this will crash in the printf function, most likely also in re_printf.
this code is a programming error, and it is not easy for the printf functions
to detect this.

I think we should have similar behaviour as GNU libc.

**Comment by lgrahl** [comment]
I completely understand your point regarding the behaviour (although I don't think it's a wise idea that `printf` ignores unknown format specifiers). I stumbled across this issue when using the `PRI...` macros. We can expect `printf` to be able to handle these format specifiers as it ships with the `PRI...` macros (more or less). That's not entirely true for re's format handler as re may or may not be able to handle these format specifiers. And because the format specifiers of these macros varies from platform to platform, we do not know beforehand whether re is able to handle it or not. In my mind, that difference legitimises a stricter handling of format specifiers.

**Comment by alfredh** [comment]
so you are suggesting that if an unknown format specifier is detected, we simply
break the loop and return EINVAL ?

something like:

```
default:
	-ch = '?';
	-err |= vph(&ch, 1, arg);
	+return EINVAL;

```

not a bad idea :) let me think about ..

**Comment by alfredh** [comment]
after some thinking, I think we should keep the current logic, i.e. not break the
loop if an unsupported formatter is detected.

**Comment by lgrahl** [comment]
Now that #49 has been rejected, maybe you'd be willing to accept a PR that enables to set a handler for such unknown format specifiers? This is just a wild idea so far but I think it would work if that handler has access to all internal variables (these could be passed as a struct).

**Comment by alfredh** [comment]
can you please describe how this handler would work (for example some pseudo code)?

if the handler has to be stored in global address space in print.c I'm afraid it is not such
a good solution, as we are trying to avoid global/static data and keep most of the code
fully re-entrant ... :)

**Comment by lgrahl** [comment]
I fear it would have to be registered somewhere globally (at least I don't see an obvious alternative to that). If global is not an option, I'll need to think.

**Comment by lgrahl** [comment]
So, this is the idea...

Vars that the handler can modify can be stored in a struct:

```c
struct vhprintf_vars {
    bool handled;
    uint8_t base;
    bool fm;
    enum length_modifier lenmod;
    ...
};
```

An important aspect would have to be the discussion about which variables will be handed out.

The handler could be called in the following way in `re_vhprintf`:

```c
...
for (;*p && !err; p++) {
    ...

    vars.handled = false;
    vars.fm = false;
    vars.base = 10;

    if (format_specifier_handler)
    err |= format_specifier_handler(*p, &vars, &ap);
    if (!vars.handled || err) {
        switch (*p) {

        case '-':
            ...
        }
    }
    
    if (!vars.fm)
        p0 = p + 1;
```

I haven't found a convenient alternative to storing the handler globally (as done in `dbg.c` and `main.c`).

**Comment by lgrahl** [comment]
Ping! What do you think - would storing the handler globally (as done in `dbg.c`) be okay or is it a no-no?

**Comment by alfredh** [comment]
I am quite sceptical about adding such a complex solution, just to detect that
a wrong modifier is used. I think we should just keep the current code as is ..

**Comment by lgrahl** [comment]
If that's not an option, okay.

Then I only have one question left: Why should the loop not be stopped in case an unknown format specifier has been found? Is there a corner case for this I've overseen?

**Comment by alfredh** [comment]
you can try this test program:

```
int main()
{
	printf   ("libc:   '%y' '%y' '%y' '%y'\n", 0, 0, 0, 0);
	re_printf("re:     '%y' '%y' '%y' '%y'\n", 0, 0, 0, 0);

	re_printf("this %y is a long debug log message ...\n");
}
```


output:

```
./test 
libc:   'y' 'y' 'y' 'y'
re:     '?' '?' '?' '?'
this ? is a long debug log message ...
```

so the behaviour of libre's re_printf is similar to libc.

if the loop would break at unknown modifiers, in this case 'y', the last
line would be:

```
this (without the newline)
```

normally the return value of re_printf(stdout/stderr, "") or DEBUG_xxx functions
are not checked. another usecase is e.g. re_sdprintf() which will most of the time
check the return value.

so I think we should keep the current logic.

**Comment by lgrahl** [comment]
In every case I can think of, an unknown format specifier is a bug. If that's the case, why continue? It doesn't make any sense to me. With either of the possible output you've shown, you know that something went wrong and you have to fix it. Heck, maybe even print `unknown format specifier in line <no>` if that helps.

Deviating from libc will not hurt in my eyes as this would only change behaviour of the code in case you've made a programming mistake.

**Comment by czarkoff** [comment]
FWIW I would expect `re_printf()` to behave like `printf()`, so printing format specifier letter instead of question mark makes more sense to me, Debugging message about wrong specifier would make sense as well, but only is debugging is on.

**Comment by alfredh** [comment]
I will keep the current code as is, hence no changes needed.
