### ISSUE TITLE
Mailing list not reachable

### ISSUE THREAD

**Issue by andreygursky** [creytiv/re#74]
> Contact
Please join our subscription-only mailing-list for discussions and updates. 

The server http://lists.creytiv.com/mailman/listinfo/re-devel disappeared.

```
$ ping lists.creytiv.com
ping: lists.creytiv.com: Name or service not known
```

**Comment by richaas** [comment]
Our server died recently. We are working to restore it.

	Richard

**Comment by andreygursky** [comment]
> Our server died recently. We are working to restore it. 

Richard, thanks for info.

Andrey

**Comment by alfredh** [comment]
it is up again:

http://lists.creytiv.com/mailman/listinfo/re-devel

We lost all the subscribers .. Everybody please subscribe again :)
