### ISSUE TITLE
latest debian/changelog entry has wrong month syntax

### ISSUE THREAD

**Issue by juha-h** [creytiv/re#77]
Latest debian/changelog entry has wrong month syntax.  Sept should be changed to Sep.  Otherwise building of Debian package complains:

dpkg-buildpackage: warning:     debian/changelog(l5): invalid abbreviated month name 'Sept'
LINE:  -- Alfred E. Heggestad <alfred.heggestad@gmail.com>  Tue, 5 Sept 2017 12:00:00 +0200
dpkg-buildpackage: warning:     debian/changelog(l5): cannot parse non-comformant date '5 Sept 2017 12:00:00 +0200'
LINE:  -- Alfred E. Heggestad <alfred.heggestad@gmail.com>  Tue, 5 Sept 2017 12:00:00 +0200

**Comment by alfredh** [comment]
Thanks for reporting :)
