### ISSUE TITLE
How to create registrar server?

### ISSUE THREAD

**Issue by vit1251** [creytiv/re#87]
Hello could you explain how to make high-level architicture for registrar service and handle incoming register?

**Comment by alfredh** [comment]
Hi,

you need to install a handler for handling incoming REGISTER messages,
using the `sip_listen` function.

baresip's test framework has a fully functional SIP-proxy.
you can read the source code here:

https://github.com/alfredh/baresip/blob/master/test/sip/sipsrv.c#L46

/Alfred

**Comment by alfredh** [comment]
this kind of question is better suited for the mailing-list:

http://lists.creytiv.com/mailman/listinfo/re-devel
